version: '3.8'

services:

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Agarwal_77
      MYSQL_DATABASE: email_summarizer_db
      MYSQL_PASSWORD: Agarwal_77

  
