# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-app-ip-service
# spec:
#   selector:
#     app: flask-app
#   ports:
#   - protocol: TCP
#     port: 5000
#     targetPort: 5000
#   type: NodePort



# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-app
# spec:
#   selector:
#     app: flask-app
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 5000
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: flask-app-ip-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
